/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.govcloud.digst;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Represents an Organisation */
@org.apache.avro.specific.AvroGenerated
public class Organisation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1580982900855633911L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Organisation\",\"namespace\":\"com.govcloud.digst\",\"doc\":\"Represents an Organisation\",\"fields\":[{\"name\":\"name\",\"type\":\"string\",\"doc\":\"The name of the community\"},{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"parentid\",\"type\":\"string\"},{\"name\":\"template\",\"type\":\"string\"},{\"name\":\"cvr\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"foaauthorityid\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"email\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"website\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"telephonenumber\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"housenumber\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"streetname\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"postcode\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"district\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"faxnumber\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"municipalitycode\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"extras\",\"type\":{\"type\":\"map\",\"values\":\"string\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Organisation> ENCODER =
      new BinaryMessageEncoder<Organisation>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Organisation> DECODER =
      new BinaryMessageDecoder<Organisation>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Organisation> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Organisation> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Organisation>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Organisation to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Organisation from a ByteBuffer. */
  public static Organisation fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** The name of the community */
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence id;
  @Deprecated public java.lang.CharSequence parentid;
  @Deprecated public java.lang.CharSequence template;
  @Deprecated public java.lang.CharSequence cvr;
  @Deprecated public java.lang.CharSequence foaauthorityid;
  @Deprecated public java.lang.CharSequence email;
  @Deprecated public java.lang.CharSequence website;
  @Deprecated public java.lang.CharSequence telephonenumber;
  @Deprecated public java.lang.CharSequence housenumber;
  @Deprecated public java.lang.CharSequence streetname;
  @Deprecated public java.lang.CharSequence postcode;
  @Deprecated public java.lang.CharSequence district;
  @Deprecated public java.lang.CharSequence faxnumber;
  @Deprecated public java.lang.CharSequence municipalitycode;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> extras;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Organisation() {}

  /**
   * All-args constructor.
   * @param name The name of the community
   * @param id The new value for id
   * @param parentid The new value for parentid
   * @param template The new value for template
   * @param cvr The new value for cvr
   * @param foaauthorityid The new value for foaauthorityid
   * @param email The new value for email
   * @param website The new value for website
   * @param telephonenumber The new value for telephonenumber
   * @param housenumber The new value for housenumber
   * @param streetname The new value for streetname
   * @param postcode The new value for postcode
   * @param district The new value for district
   * @param faxnumber The new value for faxnumber
   * @param municipalitycode The new value for municipalitycode
   * @param extras The new value for extras
   */
  public Organisation(java.lang.CharSequence name, java.lang.CharSequence id, java.lang.CharSequence parentid, java.lang.CharSequence template, java.lang.CharSequence cvr, java.lang.CharSequence foaauthorityid, java.lang.CharSequence email, java.lang.CharSequence website, java.lang.CharSequence telephonenumber, java.lang.CharSequence housenumber, java.lang.CharSequence streetname, java.lang.CharSequence postcode, java.lang.CharSequence district, java.lang.CharSequence faxnumber, java.lang.CharSequence municipalitycode, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> extras) {
    this.name = name;
    this.id = id;
    this.parentid = parentid;
    this.template = template;
    this.cvr = cvr;
    this.foaauthorityid = foaauthorityid;
    this.email = email;
    this.website = website;
    this.telephonenumber = telephonenumber;
    this.housenumber = housenumber;
    this.streetname = streetname;
    this.postcode = postcode;
    this.district = district;
    this.faxnumber = faxnumber;
    this.municipalitycode = municipalitycode;
    this.extras = extras;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return id;
    case 2: return parentid;
    case 3: return template;
    case 4: return cvr;
    case 5: return foaauthorityid;
    case 6: return email;
    case 7: return website;
    case 8: return telephonenumber;
    case 9: return housenumber;
    case 10: return streetname;
    case 11: return postcode;
    case 12: return district;
    case 13: return faxnumber;
    case 14: return municipalitycode;
    case 15: return extras;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: id = (java.lang.CharSequence)value$; break;
    case 2: parentid = (java.lang.CharSequence)value$; break;
    case 3: template = (java.lang.CharSequence)value$; break;
    case 4: cvr = (java.lang.CharSequence)value$; break;
    case 5: foaauthorityid = (java.lang.CharSequence)value$; break;
    case 6: email = (java.lang.CharSequence)value$; break;
    case 7: website = (java.lang.CharSequence)value$; break;
    case 8: telephonenumber = (java.lang.CharSequence)value$; break;
    case 9: housenumber = (java.lang.CharSequence)value$; break;
    case 10: streetname = (java.lang.CharSequence)value$; break;
    case 11: postcode = (java.lang.CharSequence)value$; break;
    case 12: district = (java.lang.CharSequence)value$; break;
    case 13: faxnumber = (java.lang.CharSequence)value$; break;
    case 14: municipalitycode = (java.lang.CharSequence)value$; break;
    case 15: extras = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The name of the community
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * The name of the community
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'parentid' field.
   * @return The value of the 'parentid' field.
   */
  public java.lang.CharSequence getParentid() {
    return parentid;
  }

  /**
   * Sets the value of the 'parentid' field.
   * @param value the value to set.
   */
  public void setParentid(java.lang.CharSequence value) {
    this.parentid = value;
  }

  /**
   * Gets the value of the 'template' field.
   * @return The value of the 'template' field.
   */
  public java.lang.CharSequence getTemplate() {
    return template;
  }

  /**
   * Sets the value of the 'template' field.
   * @param value the value to set.
   */
  public void setTemplate(java.lang.CharSequence value) {
    this.template = value;
  }

  /**
   * Gets the value of the 'cvr' field.
   * @return The value of the 'cvr' field.
   */
  public java.lang.CharSequence getCvr() {
    return cvr;
  }

  /**
   * Sets the value of the 'cvr' field.
   * @param value the value to set.
   */
  public void setCvr(java.lang.CharSequence value) {
    this.cvr = value;
  }

  /**
   * Gets the value of the 'foaauthorityid' field.
   * @return The value of the 'foaauthorityid' field.
   */
  public java.lang.CharSequence getFoaauthorityid() {
    return foaauthorityid;
  }

  /**
   * Sets the value of the 'foaauthorityid' field.
   * @param value the value to set.
   */
  public void setFoaauthorityid(java.lang.CharSequence value) {
    this.foaauthorityid = value;
  }

  /**
   * Gets the value of the 'email' field.
   * @return The value of the 'email' field.
   */
  public java.lang.CharSequence getEmail() {
    return email;
  }

  /**
   * Sets the value of the 'email' field.
   * @param value the value to set.
   */
  public void setEmail(java.lang.CharSequence value) {
    this.email = value;
  }

  /**
   * Gets the value of the 'website' field.
   * @return The value of the 'website' field.
   */
  public java.lang.CharSequence getWebsite() {
    return website;
  }

  /**
   * Sets the value of the 'website' field.
   * @param value the value to set.
   */
  public void setWebsite(java.lang.CharSequence value) {
    this.website = value;
  }

  /**
   * Gets the value of the 'telephonenumber' field.
   * @return The value of the 'telephonenumber' field.
   */
  public java.lang.CharSequence getTelephonenumber() {
    return telephonenumber;
  }

  /**
   * Sets the value of the 'telephonenumber' field.
   * @param value the value to set.
   */
  public void setTelephonenumber(java.lang.CharSequence value) {
    this.telephonenumber = value;
  }

  /**
   * Gets the value of the 'housenumber' field.
   * @return The value of the 'housenumber' field.
   */
  public java.lang.CharSequence getHousenumber() {
    return housenumber;
  }

  /**
   * Sets the value of the 'housenumber' field.
   * @param value the value to set.
   */
  public void setHousenumber(java.lang.CharSequence value) {
    this.housenumber = value;
  }

  /**
   * Gets the value of the 'streetname' field.
   * @return The value of the 'streetname' field.
   */
  public java.lang.CharSequence getStreetname() {
    return streetname;
  }

  /**
   * Sets the value of the 'streetname' field.
   * @param value the value to set.
   */
  public void setStreetname(java.lang.CharSequence value) {
    this.streetname = value;
  }

  /**
   * Gets the value of the 'postcode' field.
   * @return The value of the 'postcode' field.
   */
  public java.lang.CharSequence getPostcode() {
    return postcode;
  }

  /**
   * Sets the value of the 'postcode' field.
   * @param value the value to set.
   */
  public void setPostcode(java.lang.CharSequence value) {
    this.postcode = value;
  }

  /**
   * Gets the value of the 'district' field.
   * @return The value of the 'district' field.
   */
  public java.lang.CharSequence getDistrict() {
    return district;
  }

  /**
   * Sets the value of the 'district' field.
   * @param value the value to set.
   */
  public void setDistrict(java.lang.CharSequence value) {
    this.district = value;
  }

  /**
   * Gets the value of the 'faxnumber' field.
   * @return The value of the 'faxnumber' field.
   */
  public java.lang.CharSequence getFaxnumber() {
    return faxnumber;
  }

  /**
   * Sets the value of the 'faxnumber' field.
   * @param value the value to set.
   */
  public void setFaxnumber(java.lang.CharSequence value) {
    this.faxnumber = value;
  }

  /**
   * Gets the value of the 'municipalitycode' field.
   * @return The value of the 'municipalitycode' field.
   */
  public java.lang.CharSequence getMunicipalitycode() {
    return municipalitycode;
  }

  /**
   * Sets the value of the 'municipalitycode' field.
   * @param value the value to set.
   */
  public void setMunicipalitycode(java.lang.CharSequence value) {
    this.municipalitycode = value;
  }

  /**
   * Gets the value of the 'extras' field.
   * @return The value of the 'extras' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getExtras() {
    return extras;
  }

  /**
   * Sets the value of the 'extras' field.
   * @param value the value to set.
   */
  public void setExtras(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.extras = value;
  }

  /**
   * Creates a new Organisation RecordBuilder.
   * @return A new Organisation RecordBuilder
   */
  public static com.govcloud.digst.Organisation.Builder newBuilder() {
    return new com.govcloud.digst.Organisation.Builder();
  }

  /**
   * Creates a new Organisation RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Organisation RecordBuilder
   */
  public static com.govcloud.digst.Organisation.Builder newBuilder(com.govcloud.digst.Organisation.Builder other) {
    return new com.govcloud.digst.Organisation.Builder(other);
  }

  /**
   * Creates a new Organisation RecordBuilder by copying an existing Organisation instance.
   * @param other The existing instance to copy.
   * @return A new Organisation RecordBuilder
   */
  public static com.govcloud.digst.Organisation.Builder newBuilder(com.govcloud.digst.Organisation other) {
    return new com.govcloud.digst.Organisation.Builder(other);
  }

  /**
   * RecordBuilder for Organisation instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Organisation>
    implements org.apache.avro.data.RecordBuilder<Organisation> {

    /** The name of the community */
    private java.lang.CharSequence name;
    private java.lang.CharSequence id;
    private java.lang.CharSequence parentid;
    private java.lang.CharSequence template;
    private java.lang.CharSequence cvr;
    private java.lang.CharSequence foaauthorityid;
    private java.lang.CharSequence email;
    private java.lang.CharSequence website;
    private java.lang.CharSequence telephonenumber;
    private java.lang.CharSequence housenumber;
    private java.lang.CharSequence streetname;
    private java.lang.CharSequence postcode;
    private java.lang.CharSequence district;
    private java.lang.CharSequence faxnumber;
    private java.lang.CharSequence municipalitycode;
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> extras;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.govcloud.digst.Organisation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.parentid)) {
        this.parentid = data().deepCopy(fields()[2].schema(), other.parentid);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.template)) {
        this.template = data().deepCopy(fields()[3].schema(), other.template);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.cvr)) {
        this.cvr = data().deepCopy(fields()[4].schema(), other.cvr);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.foaauthorityid)) {
        this.foaauthorityid = data().deepCopy(fields()[5].schema(), other.foaauthorityid);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.email)) {
        this.email = data().deepCopy(fields()[6].schema(), other.email);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.website)) {
        this.website = data().deepCopy(fields()[7].schema(), other.website);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.telephonenumber)) {
        this.telephonenumber = data().deepCopy(fields()[8].schema(), other.telephonenumber);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.housenumber)) {
        this.housenumber = data().deepCopy(fields()[9].schema(), other.housenumber);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.streetname)) {
        this.streetname = data().deepCopy(fields()[10].schema(), other.streetname);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.postcode)) {
        this.postcode = data().deepCopy(fields()[11].schema(), other.postcode);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.district)) {
        this.district = data().deepCopy(fields()[12].schema(), other.district);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.faxnumber)) {
        this.faxnumber = data().deepCopy(fields()[13].schema(), other.faxnumber);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.municipalitycode)) {
        this.municipalitycode = data().deepCopy(fields()[14].schema(), other.municipalitycode);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.extras)) {
        this.extras = data().deepCopy(fields()[15].schema(), other.extras);
        fieldSetFlags()[15] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Organisation instance
     * @param other The existing instance to copy.
     */
    private Builder(com.govcloud.digst.Organisation other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.id)) {
        this.id = data().deepCopy(fields()[1].schema(), other.id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.parentid)) {
        this.parentid = data().deepCopy(fields()[2].schema(), other.parentid);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.template)) {
        this.template = data().deepCopy(fields()[3].schema(), other.template);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.cvr)) {
        this.cvr = data().deepCopy(fields()[4].schema(), other.cvr);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.foaauthorityid)) {
        this.foaauthorityid = data().deepCopy(fields()[5].schema(), other.foaauthorityid);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.email)) {
        this.email = data().deepCopy(fields()[6].schema(), other.email);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.website)) {
        this.website = data().deepCopy(fields()[7].schema(), other.website);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.telephonenumber)) {
        this.telephonenumber = data().deepCopy(fields()[8].schema(), other.telephonenumber);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.housenumber)) {
        this.housenumber = data().deepCopy(fields()[9].schema(), other.housenumber);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.streetname)) {
        this.streetname = data().deepCopy(fields()[10].schema(), other.streetname);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.postcode)) {
        this.postcode = data().deepCopy(fields()[11].schema(), other.postcode);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.district)) {
        this.district = data().deepCopy(fields()[12].schema(), other.district);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.faxnumber)) {
        this.faxnumber = data().deepCopy(fields()[13].schema(), other.faxnumber);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.municipalitycode)) {
        this.municipalitycode = data().deepCopy(fields()[14].schema(), other.municipalitycode);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.extras)) {
        this.extras = data().deepCopy(fields()[15].schema(), other.extras);
        fieldSetFlags()[15] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * The name of the community
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * The name of the community
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * The name of the community
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * The name of the community
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder setId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder clearId() {
      id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'parentid' field.
      * @return The value.
      */
    public java.lang.CharSequence getParentid() {
      return parentid;
    }

    /**
      * Sets the value of the 'parentid' field.
      * @param value The value of 'parentid'.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder setParentid(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.parentid = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'parentid' field has been set.
      * @return True if the 'parentid' field has been set, false otherwise.
      */
    public boolean hasParentid() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'parentid' field.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder clearParentid() {
      parentid = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'template' field.
      * @return The value.
      */
    public java.lang.CharSequence getTemplate() {
      return template;
    }

    /**
      * Sets the value of the 'template' field.
      * @param value The value of 'template'.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder setTemplate(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.template = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'template' field has been set.
      * @return True if the 'template' field has been set, false otherwise.
      */
    public boolean hasTemplate() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'template' field.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder clearTemplate() {
      template = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'cvr' field.
      * @return The value.
      */
    public java.lang.CharSequence getCvr() {
      return cvr;
    }

    /**
      * Sets the value of the 'cvr' field.
      * @param value The value of 'cvr'.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder setCvr(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.cvr = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'cvr' field has been set.
      * @return True if the 'cvr' field has been set, false otherwise.
      */
    public boolean hasCvr() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'cvr' field.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder clearCvr() {
      cvr = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'foaauthorityid' field.
      * @return The value.
      */
    public java.lang.CharSequence getFoaauthorityid() {
      return foaauthorityid;
    }

    /**
      * Sets the value of the 'foaauthorityid' field.
      * @param value The value of 'foaauthorityid'.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder setFoaauthorityid(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.foaauthorityid = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'foaauthorityid' field has been set.
      * @return True if the 'foaauthorityid' field has been set, false otherwise.
      */
    public boolean hasFoaauthorityid() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'foaauthorityid' field.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder clearFoaauthorityid() {
      foaauthorityid = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'email' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmail() {
      return email;
    }

    /**
      * Sets the value of the 'email' field.
      * @param value The value of 'email'.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder setEmail(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.email = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'email' field has been set.
      * @return True if the 'email' field has been set, false otherwise.
      */
    public boolean hasEmail() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'email' field.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder clearEmail() {
      email = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'website' field.
      * @return The value.
      */
    public java.lang.CharSequence getWebsite() {
      return website;
    }

    /**
      * Sets the value of the 'website' field.
      * @param value The value of 'website'.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder setWebsite(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.website = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'website' field has been set.
      * @return True if the 'website' field has been set, false otherwise.
      */
    public boolean hasWebsite() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'website' field.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder clearWebsite() {
      website = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'telephonenumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getTelephonenumber() {
      return telephonenumber;
    }

    /**
      * Sets the value of the 'telephonenumber' field.
      * @param value The value of 'telephonenumber'.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder setTelephonenumber(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.telephonenumber = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'telephonenumber' field has been set.
      * @return True if the 'telephonenumber' field has been set, false otherwise.
      */
    public boolean hasTelephonenumber() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'telephonenumber' field.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder clearTelephonenumber() {
      telephonenumber = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'housenumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getHousenumber() {
      return housenumber;
    }

    /**
      * Sets the value of the 'housenumber' field.
      * @param value The value of 'housenumber'.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder setHousenumber(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.housenumber = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'housenumber' field has been set.
      * @return True if the 'housenumber' field has been set, false otherwise.
      */
    public boolean hasHousenumber() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'housenumber' field.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder clearHousenumber() {
      housenumber = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'streetname' field.
      * @return The value.
      */
    public java.lang.CharSequence getStreetname() {
      return streetname;
    }

    /**
      * Sets the value of the 'streetname' field.
      * @param value The value of 'streetname'.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder setStreetname(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.streetname = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'streetname' field has been set.
      * @return True if the 'streetname' field has been set, false otherwise.
      */
    public boolean hasStreetname() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'streetname' field.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder clearStreetname() {
      streetname = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'postcode' field.
      * @return The value.
      */
    public java.lang.CharSequence getPostcode() {
      return postcode;
    }

    /**
      * Sets the value of the 'postcode' field.
      * @param value The value of 'postcode'.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder setPostcode(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.postcode = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'postcode' field has been set.
      * @return True if the 'postcode' field has been set, false otherwise.
      */
    public boolean hasPostcode() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'postcode' field.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder clearPostcode() {
      postcode = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'district' field.
      * @return The value.
      */
    public java.lang.CharSequence getDistrict() {
      return district;
    }

    /**
      * Sets the value of the 'district' field.
      * @param value The value of 'district'.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder setDistrict(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.district = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'district' field has been set.
      * @return True if the 'district' field has been set, false otherwise.
      */
    public boolean hasDistrict() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'district' field.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder clearDistrict() {
      district = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'faxnumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getFaxnumber() {
      return faxnumber;
    }

    /**
      * Sets the value of the 'faxnumber' field.
      * @param value The value of 'faxnumber'.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder setFaxnumber(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.faxnumber = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'faxnumber' field has been set.
      * @return True if the 'faxnumber' field has been set, false otherwise.
      */
    public boolean hasFaxnumber() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'faxnumber' field.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder clearFaxnumber() {
      faxnumber = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'municipalitycode' field.
      * @return The value.
      */
    public java.lang.CharSequence getMunicipalitycode() {
      return municipalitycode;
    }

    /**
      * Sets the value of the 'municipalitycode' field.
      * @param value The value of 'municipalitycode'.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder setMunicipalitycode(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.municipalitycode = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'municipalitycode' field has been set.
      * @return True if the 'municipalitycode' field has been set, false otherwise.
      */
    public boolean hasMunicipalitycode() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'municipalitycode' field.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder clearMunicipalitycode() {
      municipalitycode = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'extras' field.
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getExtras() {
      return extras;
    }

    /**
      * Sets the value of the 'extras' field.
      * @param value The value of 'extras'.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder setExtras(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[15], value);
      this.extras = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'extras' field has been set.
      * @return True if the 'extras' field has been set, false otherwise.
      */
    public boolean hasExtras() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'extras' field.
      * @return This builder.
      */
    public com.govcloud.digst.Organisation.Builder clearExtras() {
      extras = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Organisation build() {
      try {
        Organisation record = new Organisation();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.id = fieldSetFlags()[1] ? this.id : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.parentid = fieldSetFlags()[2] ? this.parentid : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.template = fieldSetFlags()[3] ? this.template : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.cvr = fieldSetFlags()[4] ? this.cvr : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.foaauthorityid = fieldSetFlags()[5] ? this.foaauthorityid : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.email = fieldSetFlags()[6] ? this.email : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.website = fieldSetFlags()[7] ? this.website : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.telephonenumber = fieldSetFlags()[8] ? this.telephonenumber : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.housenumber = fieldSetFlags()[9] ? this.housenumber : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.streetname = fieldSetFlags()[10] ? this.streetname : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.postcode = fieldSetFlags()[11] ? this.postcode : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.district = fieldSetFlags()[12] ? this.district : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.faxnumber = fieldSetFlags()[13] ? this.faxnumber : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.municipalitycode = fieldSetFlags()[14] ? this.municipalitycode : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.extras = fieldSetFlags()[15] ? this.extras : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[15]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Organisation>
    WRITER$ = (org.apache.avro.io.DatumWriter<Organisation>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Organisation>
    READER$ = (org.apache.avro.io.DatumReader<Organisation>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
